### ISSUE TITLE
Block-scoped declerations not supported

### ISSUE THREAD

**Issue by leolux** [prog666/tabs#3]
Uncaught SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode in tabs.js line 11

I am using this polyfill: https://github.com/nicksrandall/babel-polyfill

**Comment by dderg** [comment]
give me some time, for now try to use babel, it's fun

**Comment by dderg** [comment]
there's no let or const in .es5 version, submit more details

**Comment by leolux** [comment]
No, this issue has nothing todo with the es5 version. It appears in tabs.js line 11. I also tested the es6 version in combination with the babel polyfill.

**Comment by dderg** [comment]
you have to compile it to es5 with babel and browserify, there's no "strict mode" is es6.

**Comment by leolux** [comment]
I think that the suggested compilation result would be the file tabs.es5.js. I don't get the point. I have created this issue based on this understanding:

Expected behaviour
tabs.js works in combination with the babel polyfill  without any further effort

Observed behaviour:
tabs.js produces an error in line 11

Should it work when using browserify with babelify extension? I am not familiar with those technologies yet. Therefore I don't know how to use them currently. One reason is the simplistic documentation of babelify which conists only words instead of sentences. So it is a bit hard for me to find one AHA-effect in this transforming, compiling, shimming and emulating universe :-)

**Comment by leolux** [comment]
@prog666 can you provide a demo with tabs.js? The current demo uses tabs.es5.js (http://front-end.fmake.ru/future-tabs/examples/)

**Comment by dderg** [comment]
sure, wait a little

**Comment by dderg** [comment]
check it out. in folder `examples` do `npm i && gulp`

**Comment by leolux** [comment]
That was fast, thank you!

**Comment by leolux** [comment]
The example works. But it uses the file "all.js " instead of "dist/tabs.js". 

It seems to me that this project/plugin is missing a distribution file. The file "dist/tabs.js" cannot be used as it is because it first has to be transformed by babelify (line 18 in gulpfile.js).

"all.js" cannot be used as a distribution file for this plugin as well because it is the result of a custom build project. If you could you make the file "all.js" independend from "app.js" then it would be applicable for any user of this plugin.

@prog666 I am still a noob at module standards. Therefore I am eager to know if the above explanation makes sense to you?

**Comment by dderg** [comment]
it uses app.js which compiles to all.js and module 'future-tabs' is included inside app.js. there's gulpfile which contains a task for gulp, read docs about gulp and nodejs with npm

**Comment by dderg** [comment]
to see whole example you should do the next

``` sh
sudo npm install -g gulp
cd examples
npm install
gulp
```

**Comment by dderg** [comment]
app.js is your main website script.

**Comment by prog666** [comment]
did it help?

**Comment by leolux** [comment]
No, app.js is not my main script. In general I am using this plugin only as a bower dependency. So the only thing what should happen is that bower tells the build system which file/files to include into index.html. This concept should work independent of the actual build system because it is simple a JSON file (bower.json). And I am using grunt btw. 

I still see the problem that this plugin cannot be used without a build system that transforms this plugin with babelify. The result of this transformation should be the solution to this problem because it allows me to use it right away without having to make changes to the build system.

**Comment by dderg** [comment]
it cannot be used without commonjs bulid system

**Comment by dderg** [comment]
all commonjs systems support babelify natively

**Comment by dderg** [comment]
i should probably delete this module from bower, because browserify uses npm as well as webpack

**Comment by leolux** [comment]
Currently, but is there a way to make it independend to the build system? I know a project that seems to solve this problem: https://github.com/knalli/angular-vertxbus/tree/master/dist
These files have also been transformed with babelify but the distribution files are made independent of the module system.

**Comment by dderg** [comment]
i dont need it, contribute if you do, will be glad to merge your PR

**Comment by dderg** [comment]
in this project polyfill version weights 4 times more than one without. There's no reason using es6 polyfill just for one module.

**Comment by leolux** [comment]
That's true^^

**Comment by dderg** [comment]
the problem is that in es6 you use 'export' to export module, and babel transforms it to 'module.exports', which is used in browserify, only way is to have 2 files one with export and one without
