### ISSUE TITLE
es5 version seems to depend on babel polyfill

### ISSUE THREAD

**Issue by leolux** [prog666/tabs#4]
The file tabs.es5.js works when the babel polyfill is used. But without the polyfill I get the following error:
TypeError: document.querySelectorAll(...)[Symbol.iterator] is not a function

**Comment by leolux** [comment]
The expection occurs in tabs.es5.js:213:82

**Comment by dderg** [comment]
can you create a PR with changes in README.md containing a link to polyfill?

**Comment by leolux** [comment]
I don't understand why the es5 version depends on the babel polyfill. Is it required?

**Comment by dderg** [comment]
probably yes, I never used es5 version.
