### ISSUE TITLE
Destroy method missing

### ISSUE THREAD

**Issue by leolux** [prog666/tabs#5]
In order to free resources every plugin should expose some method to destroy/stop the plugin as explained in http://acuriousanimal.com/blog/2013/02/25/things-i-learned-creating-a-jquery-plugin-part-ii/

```
    destroy: function() {
        ...
    },
```

**Comment by dderg** [comment]
not sure if memory frees, see 87fc9c0f73f945a82b8452bd49066448f322987e

**Comment by leolux** [comment]
I think it does. Removing the click listener is all you can do in this plugin. It is good practice and prevents unexpected behaviour.
