### ISSUE TITLE
exports boilerplate

### ISSUE THREAD

**Issue by leolux** [prog666/tabs#6]
The following code (required when using no commonjs) stops other plugins to work:

```
var module = {exports: {}};
var exports = module.exports;
```

In my case the plugin https://github.com/cferdinandi/smooth-scroll breaks. I hope that we can get rid of these two lines of code. The plugin "smooth-scroll" checks for the existence of the object "exports" as follows:

```
(function (root, factory) {
    if ( typeof define === 'function' && define.amd ) {
        define([], factory(root));
    } else if ( typeof exports === 'object' ) {
        module.exports = factory(root);
    } else {
        root.smoothScroll = factory(root);
    }
})(typeof global !== 'undefined' ? global : this.window || this.global, function (root) {
```

I don't know what would be the correct solution.

**Comment by dderg** [comment]
correct solution is to stop supporting es5.
